spring:
  application:
    name: Bank-ms
  batch:
    job:
      enabled: true
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      label: feat/ai-10-set-up-the-server-config
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/e-banking
