spring:
  application:
    name: Bank-ms
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      label: feat/ai-10-set-up-the-server-config

management:
  endpoints:
    web:
      exposure:
        include: 'refresh'