eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8081/eureka/

spring:
  datasource:
    url: jdbc:postgresql://pg-ai-credit-scoring-project-project22-2002.k.aivencloud.com:28624/defaultdb?sslmode=require
    username: avnadmin
    password: AVNS_iGYa-583_6rRE3zWRfe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

logging:
  level:
    com.netflix.loadbalancer: DEBUG
    com.netflix.niws.client: DEBUG
    com.netflix.discovery: INFO