spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: Bank-ms
            uri: lb://BANK-MS
            predicates:
              - Path=/clients/**
          - id: IaModel-ms
            uri: lb://IAMODEL-MS
            predicates:
              - Path=/api/predict/**
          - id: Eligibility-ms
            uri: lb://ELIGIBILITY-MS
            predicates:
              - Path=/eligibility/**

    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "http://localhost:5173"
          allowedHeaders: "*"
          allowedMethods:
              - GET
              - POST

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/e-banking
            #          on peut le recuperer depuis ce lien
            #  http://localhost:9000/realms/Zaineb_Majdi/.well-known/openid-configuration
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 9004
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8081/eureka/

jwt:
  auth:
    converter:
      resource-id: e-banking-rest-api
      principle-attribute: preferred_username