spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: Bank-ms
            uri: lb://BANK-MS
            predicates:
              - Path=/bank/**
          - id: IaModel-ms
            uri: http://127.0.0.1:8000
            predicates:
              - Path=/api/predict/**
          - id: Eligibility-ms
            uri: lb://ELIGIBILITY-MS
            predicates:
              - Path=/eligibility/**

server:
  port: 9004
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8081/eureka/