spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: oooo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  port: 8080