spring:
  application:
    name: Eligibility-ms

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999/realms/e-banking
