spring:
  application:
    name: config-server

  profiles:
    active: default

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ia-project-org/IaProject.git
          default-label: feat/ai-10-set-up-the-server-config

server:
  port: 8888
